import { afterEach, expect, it, vi } from 'vitest';
import type { Household } from '../src/types';
import { buildItems } from '../src/data/stockMaster';
const family: Household = { version: 1, prefecture: '', dwelling: 'house', adults: 2, seniors: 0, kidsInfant: 0, kidsChild: 0, pets: [], flags: { allergy: false, medication: false }, targetDays: 3 };
afterEach(() => { vi.unstubAllGlobals(); vi.resetModules(); });
it('loads a previous-version saved household without erasing notes or inventing owned quantities', async () => {
  const items = buildItems(family).map(({ ownedQty: _ownedQty, ...item }) => ({ ...item, status: 'have', ...(item.id === 'water' ? { expiry: { year: 2027, month: 8 } } : {}), ...(item.id === 'bombe' ? { requiredQty: 3 } : {}) }));
  const saved = JSON.stringify({ version: 1, state: { household: family, items, sheet: { meetingPoint: '家族の集合場所', evacSite: '避難先のメモ', memo: '残しておく家族メモ' } } });
  const data = new Map([['bousaicle:v1', saved]]);
  vi.stubGlobal('localStorage', { getItem: (key: string) => data.get(key) ?? null, setItem: (key: string, value: string) => data.set(key, value), removeItem: (key: string) => data.delete(key) });
  const { useStore } = await import('../src/store');
  const state = useStore.getState();
  expect(state.household).toEqual(family);
  expect(state.sheet.memo).toBe('残しておく家族メモ');
  expect(state.items.find(i => i.id === 'water')).toMatchObject({ status: 'have', expiry: { year: 2027, month: 8 } });
  expect(state.items.find(i => i.id === 'water')!.ownedQty).toBeUndefined();
  expect(state.items.find(i => i.id === 'bombe')!.requiredQty).toBe(6);
  expect(data.get('bousaicle:v1')).toBe(saved);
});
it('persists actual counts through target changes and a fresh application load', async () => {
  const data = new Map<string, string>();
  vi.stubGlobal('localStorage', { getItem: (key: string) => data.get(key) ?? null, setItem: (key: string, value: string) => data.set(key, value), removeItem: (key: string) => data.delete(key) });
  vi.resetModules();
  const { useStore } = await import('../src/store');
  useStore.getState().diagnose(family);
  useStore.getState().updateItem('water', { ownedQty: 9, status: 'have' });
  useStore.getState().setTargetDays(7);
  expect(useStore.getState().items.find(i => i.id === 'water')).toMatchObject({ requiredQty: 21, ownedQty: 9, status: 'need' });
  vi.resetModules();
  const { useStore: reopened } = await import('../src/store');
  expect(reopened.getState().items.find(i => i.id === 'water')).toMatchObject({ requiredQty: 21, ownedQty: 9 });
});
it('continues in memory and surfaces storage failures without a retry loop', async () => {
  vi.stubGlobal('localStorage', { getItem: () => null, setItem: () => { throw new Error('Quota exceeded'); }, removeItem: () => {} });
  vi.resetModules();
  const { useStore } = await import('../src/store');
  expect(() => useStore.getState().diagnose(family)).not.toThrow();
  await new Promise(resolve => setTimeout(resolve, 0));
  expect(useStore.getState().storageOk).toBe(false);
  expect(useStore.getState().items.length).toBeGreaterThan(0);
});
